USE [Aban360]
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (1, N'میانگین وصولی آب‌بها در کاربری-تست', N';WITH Data AS ( SELECT  c.UsageTitle , p.Amount FROM [CustomerWarehouse].dbo.Payments p JOIN [CustomerWarehouse].dbo.Clients c  ON p.CustomerNumber=c.CustomerNumber AND p.ZoneId=c.ZoneId WHERE c.ToDayJalali IS NULL AND p.RegisterDay BETWEEN ''1330/01/01'' AND @CurrentDateJalali AND c.ZoneId IN @ZoneIds ), Stats AS ( SELECT PERCENTILE_CONT(0.3) WITHIN GROUP (ORDER BY Amount) OVER() AS Q1, PERCENTILE_CONT(0.97) WITHIN GROUP (ORDER BY Amount) OVER() AS Q3, Amount, UsageTitle FROM Data ), Clean AS ( SELECT * FROM Stats WHERE Amount BETWEEN Q1 - 1.5 * (Q3 - Q1) AND Q3 + 1.5 * (Q3 - Q1) ) SELECT  UsageTitle AS [Key], AVG(Amount) AS [Value] FROM Clean GROUP BY UsageTitle ORDER BY UsageTitle', CAST(N'2025-11-11T22:40:55.220' AS DateTime), N'برنامه نویس1', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (1, N'تعداد مسکونی غیرمسکونی', N'SELECT CASE WHEN UsageId IN (0, 1, 3) THEN N''مسکونی'' ELSE N''غیرمسکونی'' END AS [Key], COUNT(*) AS [Value] FROM CustomerWarehouse.dbo.Clients WHERE ToDayJalali IS NULL GROUP BY CASE  WHEN UsageId IN (0, 1, 3) THEN N''مسکونی'' ELSE N''غیرمسکونی'' END;', CAST(N'2025-11-12T10:37:14.350' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (3, N'انشعاب واگذار شده', N';WITH CTE AS ( SELECT  RN= ROW_NUMBER() OVER (PARTITION by ZoneId , CustomerNumber ORDER BY RegisterDayJalali DESC, LocalId DESC), * From [CustomerWarehouse].dbo.Clients c Where c.ZoneId IN @ZoneIds AND c.CustomerNumber<>0 AND c.RegisterDayJalali <= @CurrentDateJalali ) Select N''انشعاب واگذار شده'' as [key], COUNT(1) as [Value] FROM CTE c WHERE c.RN=1 AND c.DeletionStateId NOT IN(1,2) AND c.WaterRequestDate BETWEEN ''1330/01/01'' AND @CurrentDateJalali ', CAST(N'2025-11-12T10:41:01.210' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (4, N'انشعاب نصب شده', N';WITH CTE AS ( SELECT  RN= ROW_NUMBER() OVER (PARTITION by ZoneId , CustomerNumber ORDER BY RegisterDayJalali DESC, LocalId DESC), * From [CustomerWarehouse].dbo.Clients c Where c.ZoneId IN @ZoneIds AND c.CustomerNumber<>0 AND c.RegisterDayJalali <= @CurrentDateJalali ) SelecT N''انشعاب نصب شده'' as [key], COUNT(1) as [Value] FROM CTE c WHERE c.RN=1 AND c.DeletionStateId NOT IN(1,2) AND c.WaterRegisterDateJalali BETWEEN ''1330/01/01'' AND @CurrentDateJalali ', CAST(N'2025-11-12T10:42:49.983' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (5, N'انشعاب واگذار شده', N';WITH CTE AS ( SELECT  RN= ROW_NUMBER() OVER (PARTITION by ZoneId , CustomerNumber ORDER BY RegisterDayJalali DESC, LocalId DESC), * From [CustomerWarehouse].dbo.Clients c Where c.ZoneId IN @ZoneIds AND c.CustomerNumber<>0 AND c.RegisterDayJalali <= @CurrentDateJalali ) Select N''انشعاب واگذار شده فاضلاب'' as [key], COUNT(1) as [Value] FROM CTE c WHERE c.RN=1 AND c.DeletionStateId NOT IN(1,2) AND c.SewageRequestDate BETWEEN ''1330/01/01'' AND @CurrentDateJalali ', CAST(N'2025-11-12T10:44:43.630' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (6, N'انشعاب نصب شده', N';WITH CTE AS ( SELECT  RN= ROW_NUMBER() OVER (PARTITION by ZoneId , CustomerNumber ORDER BY RegisterDayJalali DESC, LocalId DESC), * From [CustomerWarehouse].dbo.Clients c Where c.ZoneId IN @ZoneIds AND c.CustomerNumber<>0 AND c.RegisterDayJalali <= @CurrentDateJalali ) Select N''انشعاب نصب شده فاضلاب'' as [key], COUNT(1) as [Value] FROM CTE c WHERE c.RN=1 AND c.DeletionStateId NOT IN(1,2) AND c.SewageRegisterDateJalali BETWEEN ''1330/01/01'' AND @CurrentDateJalali ', CAST(N'2025-11-12T10:46:35.373' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (7, N'کنتورهای خراب', N';WITH CTE AS ( Select b.CounterStateCode, RN=ROW_NUMBER() OVER (PARTITION BY b.BillId ORDER BY b.RegisterDay DESC) From [CustomerWarehouse].dbo.Bills b Left Join [CustomerWarehouse].dbo.Clients c  ON b.CustomerNumber=c.CustomerNumber AND b.ZoneId=c.ZoneId Where b.ZoneId IN @ZoneIds AND b.CounterStateCode=1 AND c.ToDayJalali IS NULL AND (b.RegisterDay BETWEEN ''1330/01/01'' AND @CurrentDateJalali) ) SELECT N''کنتورهای خراب'' as [Key], COUNT(1) as [Value] FROM CTE c WHERE c.RN=1 AND c.CounterStateCode=1', CAST(N'2025-11-12T10:49:17.683' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (8, N'کنتورهای خراب تعویض شده', N'SELECT  N''کنتورهای خراب تعویض شده'' AS [Key], COUNT(*) AS [Value] FROM ( SELECT b.BillId FROM CustomerWarehouse.dbo.MeterChange mc JOIN CustomerWarehouse.dbo.Bills b ON mc.CustomerNumber = b.CustomerNumber AND mc.ZoneId = b.ZoneId GROUP BY b.BillId ) X;', CAST(N'2025-11-12T11:08:45.653' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (9, N'درآمد خالص آب‌بها', N'use CustomerWarehouse Select N''درآمد خالص آب‌بها'' as [Key], SUM(b.SumItems) as [Value] From [CustomerWarehouse].dbo.Bills b Where (b.RegisterDay BETWEEN FORMAT(DATEADD(DAY,-30, GETDATE()),''yyyy/MM/dd'',''fa-IR'') AND @CurrentDateJalali) AND b.ZoneId IN @ZoneIds AND b.TypeCode IN (1,3,4,5)', CAST(N'2025-11-12T11:17:46.217' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (10, N'درآمد ناخالص آب‌بها', N'use CustomerWarehouse Select N''درآمد ناخالص آب‌بها'' as [Key], SUM(b.SumItems) as [Value] From [CustomerWarehouse].dbo.Bills b Where (b.RegisterDay BETWEEN FORMAT(DATEADD(DAY,-30, GETDATE()),''yyyy/MM/dd'',''fa-IR'') AND @CurrentDateJalali) AND b.ZoneId IN @ZoneIds AND b.TypeCode IN (1)', CAST(N'2025-11-12T11:17:46.217' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (11, N'قرائت', N'Select N''تعداد قرائت'' as [Key], COUNT(1) as [Value] From CustomerWarehouse.dbo.Bills Where CounterStateCode NOT IN (4,7,8) AND (RegisterDay BETWEEN ''1330/01/01'' AND @CurrentDateJalali) AND ZoneId IN @ZoneIds', CAST(N'2025-12-03T10:47:32.797' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (12, N'بسته و مانع', N'Select N''تعداد بسته و مانع'' as [Key], COUNT(1) as [Value]From CustomerWarehouse.dbo.Bills Where CounterStateCode IN (4,7) AND (RegisterDay BETWEEN ''1330/01/01'' AND @CurrentDateJalali) AND ZoneId IN @ZoneIds', CAST(N'2025-12-03T10:52:36.453' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (13, N'علی‌الحساب', N'Select N''تعداد علی‌الحساب'' as [Key], COUNT(1) as [Value] From CustomerWarehouse.dbo.Bills Where CounterStateCode IN (8) AND (RegisterDay BETWEEN ''1330/01/01'' AND @CurrentDateJalali) AND ZoneId IN @ZoneIds', CAST(N'2025-12-03T10:53:15.233' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (14, N'میانگین وصولی آب‌بها در کاربری', N';WITH Data AS ( SELECT  c.UsageTitle , p.Amount FROM [CustomerWarehouse].dbo.Payments p JOIN [CustomerWarehouse].dbo.Clients c  ON p.CustomerNumber=c.CustomerNumber AND p.ZoneId=c.ZoneId WHERE c.ToDayJalali IS NULL AND p.RegisterDay BETWEEN ''1330/01/01'' AND @CurrentDateJalali AND c.ZoneId IN @ZoneIds ), Stats AS ( SELECT PERCENTILE_CONT(0.3) WITHIN GROUP (ORDER BY Amount) OVER() AS Q1, PERCENTILE_CONT(0.97) WITHIN GROUP (ORDER BY Amount) OVER() AS Q3, Amount, UsageTitle FROM Data ), Clean AS ( SELECT * FROM Stats WHERE Amount BETWEEN Q1 - 1.5 * (Q3 - Q1) AND Q3 + 1.5 * (Q3 - Q1) ) SELECT  UsageTitle AS [Key], AVG(Amount) AS [Value] FROM Clean GROUP BY UsageTitle ORDER BY UsageTitle', CAST(N'2025-12-03T10:54:41.283' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (15, N'عمر کنتور', N';WITH MeterLife AS ( SELECT LifeInDay FROM CustomerWarehouse.dbo.MeterLife WHERE ZoneId IN @ZoneIds ) SELECT N''کمتر از 10 سال'' AS [Key], COUNT(CASE WHEN LifeInDay <= 3650 THEN 1 END) AS [Value] FROM MeterLife UNION ALL SELECT N''بین 10 تا 20 سال'' AS [Key], COUNT(CASE WHEN LifeInDay > 3650 AND LifeInDay <= 7300 THEN 1 END) AS [Value] FROM MeterLife UNION ALL SELECT N''بین 20 تا 30 سال'' AS [Key], COUNT(CASE WHEN LifeInDay > 7300 AND LifeInDay <= 10950 THEN 1 END) AS [Value] FROM MeterLife UNION ALL SELECT N''بیشتر از 30 سال'' AS [Key], COUNT(CASE WHEN LifeInDay > 1095 THEN 1 END) AS [Value] FROM MeterLife', CAST(N'2025-12-03T10:55:56.837' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (16, N'کاربری و آحاد مسکونی و غیرمسکونی براساس انشعاب واگذار شده آب', N';WITH CTE AS ( SELECT  RN= ROW_NUMBER() OVER (PARTITION by ZoneId , CustomerNumber ORDER BY RegisterDayJalali DESC, LocalId DESC), UsageId, DeletionStateId, WaterRequestDate, DomesticCount as DomesticUnit, CommercialCount+OtherCount as NonDomesticUnit  From [CustomerWarehouse].dbo.Clients c Where c.ZoneId IN (@ZoneIds) AND c.CustomerNumber<>0 AND c.RegisterDayJalali <= @CurrentDateJalali ), CustomerCount as( Select COUNT(Case When c.UsageId IN (0,1,3) Then 1 Else Null End) as DomesticCount, COUNT(Case When c.UsageId NOT IN (0,1,3) Then 1 Else Null End) as NonDomesticCount, SUM(c.DomesticUnit) as DomesticUnit,SUM(c.NonDomesticUnit) as NonDomesticUint  FROM CTE c WHERE c.RN=1 AND c.DeletionStateId NOT IN(1,2) AND c.WaterRequestDate BETWEEN ''1330/01/01'' AND @CurrentDateJalali ) Select  N''مسکونی'' as [key], DomesticCount as [Value] From CustomerCount Union All Select  N''غیرمسکونی'' as [key], NonDomesticCount as [Value] From CustomerCount Union All Select N''آحاد مسکونی'' as [key], DomesticUnit as [Value] From CustomerCount Union All Select  N''آحاد غیرمسکونی'' as [key], NonDomesticUint as [Value] From CustomerCount', CAST(N'2025-12-03T10:59:54.890' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (17, N'کاربری و آحاد مسکونی و غیرمسکونی براساس انشعاب واگذار شده فاضلاب', N';WITH CTE AS( SELECT  RN= ROW_NUMBER() OVER (PARTITION by ZoneId , CustomerNumber ORDER BY RegisterDayJalali DESC, LocalId DESC), UsageId, DeletionStateId,  SewageRequestDate, DomesticCount as DomesticUnit, CommercialCount+OtherCount as NonDomesticUnit From [CustomerWarehouse].dbo.Clients c Where c.ZoneId IN @ZoneIds AND c.CustomerNumber<>0 AND c.RegisterDayJalali <= @CurrentDateJalali ), CustomerCount as( Select COUNT(Case When c.UsageId IN (0,1,3) Then 1 Else Null End) as DomesticCount, COUNT(Case When c.UsageId NOT IN (0,1,3) Then 1 Else Null End) as NonDomesticCount, SUM(c.DomesticUnit) as DomesticUnit,SUM(c.NonDomesticUnit) as NonDomesticUint FROM CTE c WHERE c.RN=1 AND c.DeletionStateId NOT IN(1,2) AND c.SewageRequestDate BETWEEN ''1330/01/01'' AND @CurrentDateJalali) Select  N''مسکونی'' as [key], DomesticCount as [Value] From CustomerCount Union All Select  N''غیرمسکونی'' as [key], NonDomesticCount as [Value] From CustomerCount	Union All Select  N''آحاد مسکونی'' as [key], DomesticUnit as [Value] From CustomerCount Union All Select  N''آحاد غیرمسکونی'' as [key], NonDomesticUint as [Value] From CustomerCount ', CAST(N'2025-12-03T11:02:26.457' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (18, N'کنتور تعویض شده', N'Select N''کنتور تعویض شده'' as [Key], COUNT(1) as [Value] From CustomerWarehouse.dbo.MeterChange Where ZoneId IN @ZoneIds AND ChangeDateJalali>=(Left(Format(GetDate() , ''yyyy/MM/dd'',''fa-ir''),4 )+''/01/01'')', CAST(N'2025-12-10T10:37:14.350' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
INSERT [ReportPool].[TileScript] ([ReportCode], [Description], [Content], [CreateDateTime], [CreatedBy], [DeleteDateTime], [DeletedBy]) VALUES (19, N'وصولی آب‌بها', N'Select  N''وصولی آب‌بها'' as [Key], SUM(Amount) as [Value] From CustomerWarehouse.dbo.Payments  Where  ZoneId IN @ZoneIds AND RegisterDay BETWEEN FORMAT(DATEADD(DAY,-30,GETDATE()),''yyyy/MM/dd'', ''fa-ir'') AND @CurrentDateJalali', CAST(N'2025-12-10T18:08:24.670' AS DateTime), N'برنامه نویس3', NULL, NULL)
GO
